### ISSUE TITLE
TLS Handshake error

### ISSUE THREAD

**Issue by Scooterkip** [rojekabc/godot-newgrounds-plugin#4]
I've tried using the sample project to get an understanding of API plugin and how to use it, the Newgrounds project I'm using it on doesn't have encryption on the API enabled and has the AppID entered. I run the sample project on desktop but each button only produces the error "_do_handshake: TLS handshake error" with the message "Response result = 5" in the projects custom output.

**Comment by PogLop** [comment]
Hi, i dont know, if you already solved your problem, but i had the same issue few days back. In order to fix it, you need to replace contents of "certs.pem" file with [this](https://raw.githubusercontent.com/godotengine/godot/master/thirdparty/certs/ca-certificates.crt). I already opened PR with updated file, so maybe it will be merged. Cheers

**Comment by rojekabc** [comment]
Yeap, the most problem is when the certificate used in TSL is changed. You need keep it up to date.
